version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_USERNAME: ${MONGODB_USERNAME}
      MONGO_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - backend-network
    volumes:
      - ./mongo/data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - private-network
    ports:
      - "80:80"

  todo-service:
    build:
      context: ./todo-service
    # ports:
    #   - "8001:8001"
    environment:
      MONGO_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/tododb
    depends_on:
      - nginx
    expose:
      - "8001"
    networks:
      - backend-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/authdb
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - todo-service
    expose:
      - "8002"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
